[book]
authors = ["Jack Falejczyk"]
language = "en"
multilingual = false
src = "src"
title = "Remote Incident Manager Private Server Manual"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
